name: Release

on:
  push:
    branches:
      - master

jobs:
  bump_version_tag:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.create_tag.outputs.new_tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Execute action anothrNick/github-tag-action
      id: create_tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch

  test:
    name: Test build
    runs-on: ubuntu-latest
    env:
      dotnet-version: 3.1.x
      url: /home/runner/work/Blue10CLI/Blue10CLI/Blue10CLI/
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal 

  build:
    needs: [bump_version_tag, test]
    name: Build and release
    runs-on: ubuntu-latest
    env:
      dotnet-version: 3.1.x
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET SDK ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore
      - name: Publish and zip
        run: |
          mkdir publish 
          dotnet publish Blue10CLI/Blue10CLI.csproj -c Release -r win-x64 --no-restore -p:PublishReadyToRun=false -p:PublishSingleFile=true --self-contained true -o publish/cli
          dotnet publish  Blue10CLI/Blue10CLIHeadless.csproj -c Release -r win-x64 --no-restore -p:PublishReadyToRun=false -p:PublishSingleFile=true --self-contained true -o publish/headless
          cp README.md publish 
          cd publish
          zip -r Blue10CLI *
          mv Blue10CLI.zip ../
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{needs.bump_version_tag.outputs.new_tag}}
          release_name: ${{needs.bump_version_tag.outputs.new_tag}}-Master-${{ github.run_id }}-${{ github.run_number }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./Blue10CLI.zip
          asset_name: Blue10CLI.zip
          asset_content_type: application/zip
