name: Bump version tag and release zipped .exe

on:
  push:
    branches:
      - master

jobs:
  bump_version_tag:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Execute action anothrNick/github-tag-action
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
  create_and_publish_release:
    needs: bump_version_tag
    runs-on: ubuntu-latest
    name: create-executable
    steps:
    - uses: actions/checkout@master
    - name: Create exectuable
      run: dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=false -p:PublishSingleFile=true --self-contained true
    - name: Copy README
      run: cp /home/runner/work/Blue10CLI/Blue10CLI/README.md /home/runner/work/Blue10CLI/Blue10CLI/Blue10CLI/bin/Release/net5.0/win-x64/publish
    - name: Upload archive as release
      uses: ncipollo/release-action@v1
      with:
        artifacts: '/home/runner/work/Blue10CLI/Blue10CLI/Blue10CLI/bin/Release/net5.0/win-x64/publish'
        token: ${{ secrets.GITHUB_TOKEN }}