name: Bump version tag and release zipped .exe

on:
  push:
    branches:
      - automatic-releases-and-semver

jobs:
  bump_version_tag:
    name: Bump version and push tag
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.create_tag.outputs.new_tag }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Execute action anothrNick/github-tag-action
      id: create_tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch
  create_and_publish_release:
    needs: bump_version_tag
    runs-on: ubuntu-latest
    name: Create and publish release
    steps:
    - uses: actions/checkout@master
    - name: Create exectuable
      run: dotnet publish -c Release -r win-x64 -p:PublishReadyToRun=false -p:PublishSingleFile=true --self-contained true
    - name: Copy README
      run: cp /home/runner/work/Blue10CLI/Blue10CLI/README.md /home/runner/work/Blue10CLI/Blue10CLI/Blue10CLI/bin/Release/net5.0/win-x64/publish
    - name: Create ZIP archive
      run: |
        cd /home/runner/work/Blue10CLI/Blue10CLI/Blue10CLI/bin/Release/net5.0/win-x64/publish
        ls
        zip release.zip *
        ls
    - name: Upload archive as release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{needs.bump_version_tag.outputs.new_tag}}
        artifacts: '/home/runner/work/Blue10CLI/Blue10CLI/Blue10CLI/bin/Release/net5.0/win-x64/publish/release.zip'
        prerelease: true